name: Maintenance checks
on:
    pull_request:
        paths:
            - '.github/workflows/**'
            - 'src/**'
            - 'build.gradle.kts'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - run: ./gradlew --no-daemon build
    format:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            # clang-format doesn't come with act's local images.
            - run: if [ -n "$ACT" ]; then apt update && apt -y install clang-format-17; fi
            - run: clang-format-17 --version
            - run: ./format.sh --check
